name: Linux

on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Install OpenGL and dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libegl1-mesa-dev libwayland-dev libxkbcommon-dev wayland-protocols
      
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.30.x'

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --target rewindviewer --parallel $(nproc)

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: rewindviewer_linux
        path: build/rewindviewer
