name: Windows

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.30.x'

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      run: cmake -S . -B build -G "Ninja Multi-Config"

    - name: Build
      run: cmake --build build --target rewindviewer --parallel --config Release

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: rewindviewer_win
        path: |
          build/Release/*.exe
          build/Release/*.dll
